# Generated by Django 5.1.7 on 2025-03-28 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specializations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('second_name', models.CharField(max_length=255)),
                ('patronymic', models.CharField(blank=True, max_length=255, null=True)),
                ('experience', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('sc_degree', models.CharField(blank=True, max_length=255, null=True)),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='specializations.specialization')),
            ],
        ),
    ]
